[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pharma_scraper"
version = "0.1.0"
dependencies = [
    "requests",
    "elsapy",
    "curl_cffi",
    "google-genai",
    "pydantic",
    "beautifulsoup4",
    "pypdf",
    "python-dotenv"
]